# Generated by Django 4.2.30 on 2026-09-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='supported_ideas',
            field=models.ManyToManyField(blank=True, related_name='supporters', to='ideas.idea', verbose_name='Supported Ideas'),
        ),
    ]
