# Generated by Django 4.2.30 on 2026-09-17 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Required supplies')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Required quantity')),
                ('is_secured', models.BooleanField(default=False, verbose_name='Is it provided?')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='ideas.idea')),
            ],
        ),
    ]
